[package]
name = "strings_set_file"
version = "0.1.0"
edition = "2021"

authors = ["Oden Shirataki <oden.srtk@gmail.com>"]

description = "Indexed data file. It uses mmap and tri-avltree."

repository = "https://github.com/OdenShirataki/strings_set_file"

keywords = ["string","file","memmap","database"]
license = "MIT"

[dependencies]
file_mmap={ path="../file_mmap" , version="0.1" }